apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: baseline
  template:
    metadata:
      labels:
        app: production-app
        deployment: baseline
    spec:
      containers:
        - image: >-
            asia.gcr.io/[GCP Project ID]/spinnaker-handson
          name: baseline-deployment
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: production-app
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: production-app
  type: ClusterIP
